# This is a basic workflow to help you get started with Actions

name: snyk_setup_scan

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: snyk/actions/setup@master
    - name: Snyk test
      run: snyk iac test
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
