# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  terraform:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_DEFAULT_REGION: us-east-1
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform init
        id: init
        run: |
           terraform init -backend-config=tfenv/config.s3.tfbackend -upgrade=true -no-color -input=false
      - name: Terraform plan
        id: plan
        run: |
          terraform plan -input=false -var account_id=${{ secrets.ACCOUNT_ID }} -var region=us-east-1 -no-color -out=tfplan
      - name: Terraform commands output
        id: tf_cmd_output
        run: |
          terraform show -json tfplan > tfplan.json
          terraform state pull > terraform.tfstate
      - name: Archive terraform plan
        uses: actions/upload-artifact@v3
        with:
          name: wftfplan
          path: tfplan.json
      - name: Archive terraform tfstate
        uses: actions/upload-artifact@v3
        with:
          name: wftfstate
          path: terraform.tfstate
